language: node_js

script: sh -c 'cd client && npm install && npm run buckle:reset && npm run build && npm run test'


node_js:
   - 8

branches:
  only:
    - /.*/

notifications:
    email: true

sudo: true
