version: "3"
services:
  api:
    container_name: one-tricks-api
    restart: always
    image: user/one-tricks-api
    ports:
      - "80:80"
    environment:
      - DEBUG=kayn:*:request:error
      - DEBUG_COLORS=true
      - NODE_ENV=production
      - MONGO_URI=mongodb://db_username:db_password@ds######.mlab.com:#####/one-tricks
      - REDIS_PASSWORD=
      - GMAIL_USERNAME=
      - GMAIL_PASSWORD=
