version: "3"
services:
  api:
    container_name: one-tricks-api
    restart: always
    build: ./api
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    ports:
      - "80:80"
    environment:
      - RIOT_LOL_API_KEY=${RIOT_LOL_API_KEY}
      - NODE_ENV=development
      - DEBUG=kayn:*
      - DEBUG_COLORS=true
      - WAIT_HOSTS=mongo:27017
#  client:
 #   container_name: one-tricks-client
  #  command: yarn start 
   # restart: always
    #build: ./client
#    ports:
 ##    - "35729:35729"
   # volumes:
    #  - ./client/src:/usr/src/app/src
#      - ./client/public:/usr/src/app/public
 #   links:
  #    - api
   # environment:
    #  - NODE_ENV=development
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  redis:
    image: "redis:alpine"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
