
version: "3"
services:
  stats:
    container_name: one-tricks-stats
    restart: always
    build: ./stats
    ports:
      - "3002:3002"
  api:
    container_name: one-tricks-api
    restart: always
    build: ./api
    links:
      - mongo
      - redis
    environment:
      - DEBUG=kayn:*
  nginx-reverse-proxy:
    container_name: nginx-reverse-proxy
    restart: always
    build: ./nginx-reverse-proxy
    ports:
      - "5000:5000"
  client:
    container_name: one-tricks-client
    restart: always
    build: ./client
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  redis:
    image: "redis:alpine"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf