version: "3"
services:
  stats:
    container_name: one-tricks-stats
    restart: always
    build: ./stats
    links:
      - redis
    ports:
      - "3002:3002"
   # environment:
    #  - DEBUG=kayn:*
  api:
    container_name: one-tricks-api
    restart: always
    build: ./api
    links:
      - mongo
      - redis
    ports:
      - "3001:3001"
    environment:
      - DEBUG=kayn:*
  client:
    container_name: one-tricks-client
    command: yarn dev
    restart: always
    build: ./client
    ports:
      - "3000:3000"
      - "35729:35729"
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/public:/usr/src/app/public
    links:
      - api
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  redis:
    image: "redis:alpine"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf